on:
    workflow_call:
        inputs:
            deploy:
                type: boolean
                description: "If true, the docs will be deployed."
                default: false

jobs:
    run-docs:
        runs-on: ubuntu-latest
        steps:
        - uses: actions/checkout@v4
        
        - name: Install uv
          uses: astral-sh/setup-uv@v5
        - name: Install dependencies
          run: |
            uv pip install mkdocs mkdocs-material mkdocs-jupyter
            
        - name: Build docs
          run: mkdocs build --verbose --clean
          
        - name: Build and push docs
          if: inputs.deploy
          run: mkdocs gh-deploy --force
